#!/usr/bin/env python3

import sys

from sync_hooks import maybe_run_sync, parse_state_dir


def main() -> int:
    try:
        state_dir = parse_state_dir(sys.argv)
    except ValueError as error:
        _ = sys.stderr.write(f"{error}\n")
        return 1
    return maybe_run_sync(
        state_dir=state_dir,
        filestamp_name=".last-on-launch-sync",
        lock_name=".on-launch-sync.lock",
    )


if __name__ == "__main__":
    raise SystemExit(main())
