#!/usr/bin/env bash
set -euo pipefail

unset gh_repo glab_repo
git remote get-url origin 2>/dev/null | grep -q 'github.com' && gh_repo=1
git remote get-url origin 2>/dev/null | grep -q 'gitlab.com' && glab_repo=1

if [[ -z "${gh_repo:-}" && -z "${glab_repo:-}" ]]; then
  echo "No remote repository found. Please set up a remote repository on GitHub or GitLab."
  exit 1
fi

if [[ -n "${gh_repo:-}" ]]; then
  command -v gh 2>/dev/null || {
    echo "Executable 'gh' not found"
    exit 1
  }

  gh issue create --editor
  exit 0
fi

if [[ -n "${glab_repo:-}" ]]; then
  command -v glab 2>/dev/null || {
    echo "Executable 'glab' not found"
    exit 1
  }

  glab issue create --editor
  exit 0
fi
