#!/usr/bin/env bash
set -euo pipefail
trap 'echo "pbpaste failed on line $LINENO: $BASH_COMMAND" >&2; exit 1' ERR

if command -v xsel >/dev/null; then
  exec xsel -o -b

elif command -v xclip >/dev/null; then
  exec xclip -selection clipboard -out

elif command -v wl-paste >/dev/null; then
  exec wl-paste

else
  echo "No clipboard tool found" >&2
  exit 1
fi
