#!/usr/bin/env bash
set -euo pipefail

sudo nixos-rebuild switch
sudo nix profile wipe-history --profile /nix/var/nix/profiles/system
sudo nix-collect-garbage --delete-old
sudo nix store optimise

home-manager switch
nix profile wipe-history
nix profile wipe-history --profile ~/.local/state/nix/profiles/home-manager
nix-collect-garbage --delete-old
nix store optimise
